package: massif
version: 2.0.0
author: Yves Torres
supportpage: massif.ch

requires:
  redaxo: '^5.13.0'
  php:
    version: '>=8.1'

installer_ignore:
  - .DS_Store
  - .git
  - .gitignore
  - node_modules

page:
  title: 'MASSIF'
  perm: massif[]
  subpages:
    converter:
      title: 'MASSIF Redaxo 4 zu 5 Converter'
      perm: massif_convert[]
      icon: rex-icon fa-wrench
      customPage: true
    template:
      title: 'Template'
      icon: rex-icon fa-newspaper
      yform/table: ''
      customPage: false
      customPagePath:
      package:
      pjax: true
      hidden: true
    frontend:
      title: 'MASSIF Frontend'
      icon: rex-icon fa-rocket
      customPage: true

console_commands:
  massif:exec-php: console_massif_execute_php
