package: massif
version: 1.0.0
author: Yves Torres
supportpage: massif.ch

page:
  title: 'MASSIF'
  perm: massif[]
  subpages:
    converter:
      title: 'MASSIF Redaxo 4 zu 5 Converter'
      perm: massif_convert[]
      icon: rex-icon fa-wrench
      customPage: true
    template:
      title: 'Template'
      icon: rex-icon fa-newspaper
      yform/table: ''
      customPage: false
      customPagePath:
      package:
      pjax: true
      hidden: true

console_commands:
  massif:exec-php: console_massif_execute_php
